name = "AutomotiveDrivingModels"
uuid = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
repo = "https://github.com/sisl/AutomotiveDrivingModels.jl.git"
version = "0.8.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tricks = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"

[compat]
julia = "1.3"
AutoViz = "0.8, 0.9"

[extras]
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AutoViz", "Cairo", "ForwardDiff", "Reel", "Test"]
